export const REQUEST_GET_CHECKLIST = "REQUEST_GET_CHECKLIST";
export const REQUEST_GET_CHECKLIST_SUCCESS = "REQUEST_GET_CHECKLIST_SUCCESS";
export const REQUEST_GET_CHECKLIST_FAILURE = "REQUEST_GET_CHECKLIST_FAILURE";